VIA_ENABLE         = yes
VIAL_ENABLE        = yes
ENCODER_MAP_ENABLE = yes
REPEAT_KEY_ENABLE  = yes

RGB_MATRIX_ENABLE  = yes
VIALRGB_ENABLE     = yes
RGBLIGHT_MODE_STATIC_LIGHT = yes
UNICODE_ENABLE = yes
OS_DETECTION_ENABLE = yes